### ISSUE TITLE
首次运行注意事项(window平台)

### ISSUE THREAD

**Issue by seleningchan** [alchemystar/Freedom#2]
注意数据库元数据配置路径，例如：因为启动时使用`RandomAccessFile`访问文件，日志文件路径配置成具体的文件路径。
<img width="756" alt="issue" src="https://user-images.githubusercontent.com/15812343/85921281-c14b1e00-b8ad-11ea-8a1b-f791e560d708.png">

**Comment by alchemystar** [comment]
多谢
