### ISSUE TITLE
javax.servlet:servlet-api:pom:3.1这个包maven无法下载，有没有办法？

### ISSUE THREAD

**Issue by sunjianchuang** [alchemystar/Freedom#4]
<dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
            <version>3.1</version>
</dependency>
Could not find artifact javax.servlet:servlet-api:pom:3.1
我换了好几个仓库提示同样的错误，都是下载失败。

**Comment by crossoverJie** [comment]
```xml
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.0.1</version>
        </dependency>
```
可以修改为这个包。

**Comment by sunjianchuang** [comment]
> ```
>         <dependency>
>             <groupId>javax.servlet</groupId>
>             <artifactId>javax.servlet-api</artifactId>
>             <version>3.0.1</version>
>         </dependency>
> ```
> 
> 可以修改为这个包。

好使，感谢
